# Generated by Django 3.2.4 on 2021-06-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Los Barrios'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Las Parroquias'},
        ),
    ]
